### ISSUE TITLE
How to inline?

### ISSUE THREAD

**Issue by Dibbyo456** [Cweili/svelte-fa#188]
### Code:

![Screenshot 2022-07-03 180321](https://user-images.githubusercontent.com/18257605/177039885-2b275756-358a-48f4-a100-2471bb5bd4cd.png)

### Output:

![Screenshot 2022-07-03 180632](https://user-images.githubusercontent.com/18257605/177039985-996c9cf7-a215-432b-831c-812cc070fff5.png)

**Comment by Dibbyo456** [comment]
Never mind..

```
<Fa icon={faVirusCovid} class="inline" />
```

**Comment by Cweili** [comment]
@Dibbyo456 
svelte-fa generates svg element which display as a inline element by default. But tailwindcss makes svg as a block element.

```css
/*
! tailwindcss v3.1.4 | MIT License | https://tailwindcss.com
*//*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

...

/*
1. Make replaced elements `display: block` by default. (https://github.com/mozdevs/cssremedy/issues/14)
2. Add `vertical-align: middle` to align replaced elements more sensibly by default. (https://github.com/jensimmons/cssremedy/issues/14#issuecomment-634934210)
   This can trigger a poorly considered lint error in some tools but is included by design.
*/

img,
svg,
video,
canvas,
audio,
iframe,
embed,
object {
  display: block; /* 1 */
  vertical-align: middle; /* 2 */
}

...
```
