### ISSUE TITLE
add styling via class

### ISSUE THREAD

**Issue by evgenyfadeev** [Cweili/svelte-fa#84]
Maybe it's just me, but I'm unable to do this (an any other styling via "class" or "svg" selector... Is this a bug?

(My setup is with routify).

```
<style>
   .some-class {
       position: absolute;
       right: 0;
  }
</style>
<Fa class="some-class" icon={faFlag} />
```

**Comment by Cweili** [comment]
Try [apply your style globally with `:global()`](https://svelte.dev/docs#style)  like this:

```css
:global(.some-class) {
     position: absolute;
     right: 0;
}
```

Here is the [issue](https://github.com/sveltejs/svelte/issues/5236).
